FROM python:3

RUN useradd -ms /bin/bash django

ENV PYTHONUNBUFFERED 1

USER django

WORKDIR /home/django/api

ENV PATH $PATH:/home/django/.local/bin

COPY requirements.txt /home/django/api

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . /home/django/app/api